build:
    image: docker:20.10.5
    stage: build
    services:
      - docker:20.10.5-dind
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
    script:
        # Using the special CI_REGISTRY_USER variable: The user specified by this 
        # variable is created for you in order to push to the Registry connected to 
        # your project. Its password is automatically set with the CI_REGISTRY_PASSWORD 
        # variable. This allows you to automate building and deploying your Docker 
        # images and has read/write access to the Registry. This is ephemeral, so it’s 
        # only valid for one job. You can use the following example as-is:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $IMAGE_TAG .
      - docker tag $IMAGE_TAG $IMAGE_TAG_LATEST
      - docker push $IMAGE_TAG
      - docker push $IMAGE_TAG_LATEST

